---
- name: Set up base system
  ansible.builtin.import_tasks: system.yml
  tags: system
- name: Set up firewall
  ansible.builtin.import_tasks: firewall.yml
  tags: firewall
- name: Set up containers
  ansible.builtin.import_tasks: containers.yml
  tags: containers
- name: Set up vector
  ansible.builtin.import_tasks: vector.yml
  tags: vector
