---
- name: Create apt keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
- name: Download Datadog GPG key
  ansible.builtin.get_url:
    url: https://keys.datadoghq.com/DATADOG_APT_KEY_CURRENT.public
    dest: /etc/apt/keyrings/datadog-archive-keyring.asc
    mode: "0644"
- name: Add Vector repository
  ansible.builtin.deb822_repository:
    name: vector
    types: deb
    uris: https://apt.vector.dev/
    suites: stable
    components: vector-0
    signed_by: /etc/apt/keyrings/datadog-archive-keyring.asc
- name: Install vector
  ansible.builtin.apt:
    name: vector
    update_cache: true
- name: Configure Vector
  ansible.builtin.template:
    src: vector.yaml.j2
    dest: /etc/vector/vector.yaml
    mode: "0644"
  notify: Restart vector
- name: Enable and start Vector
  ansible.builtin.systemd:
    name: vector
    enabled: true
    state: started
