---
domain_name_dex: "infraid.beyondallreason.dev"
domain_name_grafana: "grafana.beyondallreason.dev"
domain_name_victoriametrics: "metrics.beyondallreason.dev"
metrics_write_password: "{{ vault_metrics_write_password }}"
dex_github: true
github_org: "beyond-all-reason"
github_client_id: "{{ vault_github_client_id }}"
github_client_secret: "{{ vault_github_client_secret }}"
victoriametrics_web_allowed: "allowed_groups=beyond-all-reason:monitoring-admins"
grafana_role_attribute_path: "contains(groups[*], 'beyond-all-reason:monitoring-admins') && 'Admin' || 'None'"
