$ANSIBLE_VAULT;1.1;AES256
30353266333737646664656136636531656364346136393032653735386537383333613833336339
6363633539633934636662613936313561643237616134620a323130313463306463363763303530
31643138633936323261336135363661383936323239343133386563323933626462353838326161
3063326465633039340a316466656365666462363934333739333230373465666231626639363865
36343733303163353634313137333765626636323438633262396532666332376163343861386665
39313962336163346465333832636138306639316563306161326566663364323630303539393061
30373666343230323033616137326539666135623632646164326666346562333930633135393434
38323638356332363139363037366633383466346466663235303966373963373535623761623961
64383131653630616265623331633539373661316165653461653532373337663836363165646633
37346433653439343561376138613465383932656166313766626635633966633861656233646330
39336537393661306636346535316563366431656538633839316563316462616666306638306436
34636435633263643566613239643564326534373739323736313335363135616361396266636138
61313435663065623837373264343865313262396432386363636233623830323838613666303439
30323663373036663764633336646237386239636235623164613765633433333330393735323038
35636533633235653138636633333931666538663638616334326631636566376165663936353037
65376365333333383065313766616132363862353965373836373963353338613035663765656561
61346365613731356638303733313166326566306463316136316335323730646263
