$ANSIBLE_VAULT;1.1;AES256
36383134306263643936313939663066616139616531633865356466316232316365336136386264
3963363164333862303430633265363731376135616239610a393035633931646563633061323562
31343262353436393731376635353066623031393531643638646465646234313739616434393633
3666616436623535660a333530393633356363646232656465616533616337373361323862346538
33643438373065336466633639303862623136633262303262363833356531313436656662643530
33316164366436613066626331323530373262396361373337663935323033316330313037623564
62333933303434333539373362643632313363353531326663323665663733663265346263326639
31313033393433656533613065653565623935646334323462306666623466333031653037663331
64303732336664353334623164623236353634306461663336346563333764356361666137323938
39633265373661636135366362613732306365316362333433316566373434623139376634663930
30663936643765653734356265353066366137653233643064313361323866643638663132343231
38633363313432306235303430396535613966626130633438373733393132393366376465393634
33623936323464336132356561366331316264643662306434623239386662363465626431663661
31613634393065636166623735663765643033316463623932333162376461653536386263373061
63373663643634316133303638383539326539643736626436383463633766393237656265343131
33363533326132336131316336336665623737636638386164613963643436356666636562356265
66363037626435363065346363373165313438313936623736393538643837643465393261663563
3930656337623235323838626536343262366165343665646265
