$ANSIBLE_VAULT;1.1;AES256
30626539303932303235663066653733343564636136613763656136316231343732666366393363
6430383430653536633265316364396438313339373431310a373266386337336238633661383139
65646531353432303238396437623337666535653931666361336532623363396166353937363839
3439333261323066620a336535633062613137326664663437363932656132326538326338663634
35653763373934356232663437623634383562313239343135663939323934353662363864323030
37303737323535626330366630366162303537656365616331353133366138613165643766616633
37316463353739343031656333646362383566386537633833386430353934646565633733363938
62656162623230326164316162623136343561333261653963383739386631333137336437393165
39626237636265313763306534396438393362323263336431626662323335316661343336366531
64633339396130616330366266313336663161386239616130343762383931643839313232643264
38333564323562396361346461613139383830303561373566373736313233613265663038373038
36666639393434613136303931663162333065326465626662376562343033353236663430383938
35393537343338633365663062323830663230613264303935303464646534656561343939653030
61323066626437353534666132353531356464363464353638333637353266363664376637346332
30306533393236336637646430373331333735646633306134613432626165343232333935333761
33366264653863363534643762643962383636653439363366373538626165383066343633386439
3838
