---
domain_name_dex: "id.bar-mon.local"
domain_name_grafana: "grafana.bar-mon.local"
domain_name_victoriametrics: "metrics.bar-mon.local"
grafana_oauth_client_id: "grafana"
oauth2proxy_oauth_client_id: "oauth2proxy"
metrics_write_user: "metrics"
metrics_write_password: "$2y$14$kzhgGvaDcRZwAKY5uZZVquOedyYXgPyJ66CejiHkuH5S6Km/jwY5K" # "metrics"
victoriametrics_web_allowed: "allowed_emails=admin@local"
