---
domain_name_dex: "id.bar-mon.local"
domain_name_grafana: "grafana.bar-mon.local"
domain_name_victoriametrics: "metrics.bar-mon.local"
grafana_oauth_client_id: "grafana"
grafana_oauth_client_secret: "393821bc1fa24c713fa637cba343f156265a55dd"
oauth2proxy_oauth_client_id: "oauth2proxy"
oauth2proxy_oauth_client_secret: "777c21f2bf18f741a306eee6c39791fe090bea93"
metrics_write_user: "metrics"
metrics_write_password: "$2y$14$kzhgGvaDcRZwAKY5uZZVquOedyYXgPyJ66CejiHkuH5S6Km/jwY5K" # "metrics"
victoriametrics_web_allowed: "allowed_emails=admin@local"
