---
- name: Restart Caddy
  ansible.builtin.systemd_service:
    name: caddy.service
    state: restarted
- name: Reload Caddy
  ansible.builtin.systemd_service:
    name: caddy.service
    state: reloaded
