---
- name: Reload systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    state: reloaded
- name: Restart Caddy
  ansible.builtin.systemd_service:
    name: caddy.service
    state: restarted
- name: Reload Caddy
  ansible.builtin.systemd_service:
    name: caddy.service
    state: reloaded
- name: Restart Dex
  ansible.builtin.systemd_service:
    name: dex.service
    state: restarted
- name: Restart Grafana
  ansible.builtin.systemd_service:
    name: grafana.service
    state: restarted
- name: Restart VictoriaMetrics
  ansible.builtin.systemd_service:
    name: victoriametrics.service
    state: restarted
- name: Restart vector
  ansible.builtin.systemd:
    name: vector
    state: restarted
